full_rebuild: true
incremental: true
source: "."
destination: "./jekyllbuild"
name: Material Theme
description: Material Theme for Jetbrains
url: https://mallowigi.github.io/material-theme-jetbrains-eap
baseurl: /material-theme-jetbrains-eap
permalink: /:title/
paginate: 6
paginate_path: /page/:num
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-toc
- algoliasearch-jekyll
infinite_scroll: false

twitter: mallowigi
twutter2: crmag
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: /img
img_folder: /img
author_default_avatar: /profile-pic.jpeg
github: https://github.com/mallowigi/material-theme-jetbrains-eap
version: 1.0.3
year: 2015-2018
social_image_path:  /assets/media/compressed/brand/material-logo.png
social_logo_path:   /assets/media/compressed/brand/material-social-logo.png

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "material-sidebar-left"
      type: "standard"
      homedisplay: "featimg"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "material-sidebar-left"
      author: "mallowigi"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

relative_permalinks: false
exclude:
  - .git
  - .gitignore
  - sass
  - js
  - vue
  - .sass-cache
  - package.json
  - gruntfile.js
  - browser-sync.js
  - .postcssrc.js
  - node_modules
  - webpack.config.js
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - .eslintrc.js
  - .eslintignore
  - .editorconfig
  - .babelrc
  - LICENCE
  - README.md
  - jekyllbuild
  - build
  - src
sass:
  style: compressed
collections:
  features:
    permalink: /:collection/:title
    output: true

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              ""
  css_hash:         ""
  js:               ""
  js_hash:          ""
  jquery:           "https://code.jquery.com/jquery-3.2.1.min.js"
  jquery_hash:      "sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
  materialize:      "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"
  materialize_hash: "sha384-C5yXM3HiWa6a8kI2Jd4LuuwmOGAVgJw0YSmuRXN+PLT5Jln26ddUnPQxkInM/w2x"

algolia:
  application_id: 77GG697EBY
  index_name: localhost
